name: null
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cycler=0.10.0=py38_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - joblib=0.15.1=py_0
  - kiwisolver=1.2.0=py38h04f5b5a_0
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - llvm-openmp=10.0.0=h28b9765_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h9aa3819_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.1=py38h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h3304bdc_1
  - openssl=1.1.1g=h1de35cc_0
  - pandas=1.0.3=py38h6c726b0_0
  - pip=20.0.2=py38_3
  - pyparsing=2.4.7=py_0
  - python=3.8.3=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - readline=8.0=h1de35cc_0
  - scikit-learn=0.22.1=py38h27c97d8_0
  - scipy=1.4.1=py38h44e99c9_0
  - setuptools=46.4.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h5c1f38d_1
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py38h1de35cc_1
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/chesterheng/Desktop/machinelearning-datascience/heart-disease-project/env

